[build]
  command = "npm run build"          
  publish = "dist"                   
  base = "."   
                        
[dev]
  command = "vite"
  port = 3000
  targetPort = 5173
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200